begin;

create table if not exists public.drafts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  local_id text not null,
  version bigint not null default 1 check (version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint draft_data_is_object check (jsonb_typeof(data) = 'object'),
  constraint draft_local_id_length check (char_length(local_id) between 1 and 160),
  constraint drafts_owner_local_id_unique unique (user_id, local_id)
);

create index if not exists drafts_owner_updated_idx
  on public.drafts (user_id, updated_at desc, id desc);

create or replace function public.enforce_draft_integrity()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.user_id is distinct from old.user_id then
    raise exception using errcode = '23514', message = 'draft_owner_is_immutable';
  end if;
  if new.local_id is distinct from old.local_id then
    raise exception using errcode = '23514', message = 'draft_local_id_is_immutable';
  end if;
  if new.created_at is distinct from old.created_at then
    raise exception using errcode = '23514', message = 'draft_created_at_is_immutable';
  end if;
  if new.data is null or jsonb_typeof(new.data) <> 'object' then
    raise exception using errcode = '22023', message = 'invalid_draft_payload';
  end if;

  new.version := old.version + 1;
  new.updated_at := clock_timestamp();
  return new;
end;
$$;

drop trigger if exists enforce_draft_integrity on public.drafts;
create trigger enforce_draft_integrity
before update on public.drafts
for each row execute function public.enforce_draft_integrity();

alter table public.drafts enable row level security;

drop policy if exists "Users can read their own drafts" on public.drafts;
create policy "Users can read their own drafts"
  on public.drafts for select
  to authenticated
  using (auth.uid() = user_id);

revoke all on public.drafts from public, anon, authenticated;
grant select on public.drafts to authenticated;

revoke all on function public.enforce_draft_integrity() from public, anon, authenticated;

commit;
