begin;

create table if not exists public.lifecycle_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  kind text not null check (kind in ('publish', 'close')),
  status text not null default 'pending'
    check (status in ('draft', 'pending', 'processing', 'action_required', 'completed')),
  scheduled_date date not null,
  payload jsonb,
  thesis_id bigint references public.theses (id) on delete cascade,
  resolved_symbol text not null,
  exchange text,
  exchange_timezone text not null,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  retry_cycle integer not null default 0 check (retry_cycle >= 0),
  next_attempt_at timestamptz,
  lease_token uuid,
  lease_expires_at timestamptz,
  last_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint lifecycle_job_payload check (
    (kind = 'publish' and payload is not null)
    or (kind = 'close' and thesis_id is not null)
  )
);

create index if not exists lifecycle_jobs_due_idx
  on public.lifecycle_jobs (status, next_attempt_at, id);

create index if not exists lifecycle_jobs_owner_idx
  on public.lifecycle_jobs (user_id, created_at desc, id desc);

create unique index if not exists lifecycle_jobs_open_close_idx
  on public.lifecycle_jobs (thesis_id)
  where kind = 'close' and status <> 'completed';

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  type text not null check (type in (
    'publication_completed', 'close_completed', 'trigger_clear',
    'trigger_warning', 'trigger_breached', 'action_required'
  )),
  title text not null,
  message text not null,
  thesis_id bigint references public.theses (id) on delete cascade,
  lifecycle_job_id bigint references public.lifecycle_jobs (id) on delete cascade,
  event_key text not null unique,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_owner_created_idx
  on public.notifications (user_id, created_at desc, id desc);

create index if not exists notifications_owner_unread_idx
  on public.notifications (user_id, created_at desc)
  where read_at is null;

alter table public.theses
  add column if not exists next_refresh_at timestamptz not null default now(),
  add column if not exists refresh_lease_token uuid,
  add column if not exists refresh_lease_expires_at timestamptz,
  add column if not exists last_refreshed_at timestamptz,
  add column if not exists refresh_failure_count integer not null default 0;

create index if not exists theses_refresh_due_idx
  on public.theses (next_refresh_at, id)
  where status = 'active';

alter table public.lifecycle_jobs enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "Users can read their own lifecycle jobs" on public.lifecycle_jobs;
create policy "Users can read their own lifecycle jobs"
  on public.lifecycle_jobs for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can read their own notifications" on public.notifications;
create policy "Users can read their own notifications"
  on public.notifications for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can mark their own notifications read" on public.notifications;
create policy "Users can mark their own notifications read"
  on public.notifications for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

revoke all on public.lifecycle_jobs from public, anon, authenticated;
grant select on public.lifecycle_jobs to authenticated;

revoke all on public.notifications from public, anon, authenticated;
grant select on public.notifications to authenticated;
grant update (read_at) on public.notifications to authenticated;

create or replace function public.create_scheduled_publication(
  p_user_id uuid,
  p_payload jsonb,
  p_scheduled_date date,
  p_resolved_symbol text,
  p_exchange text,
  p_exchange_timezone text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  job_row public.lifecycle_jobs%rowtype;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception using errcode = '22023', message = 'invalid_scheduled_payload';
  end if;
  if p_scheduled_date is null
    or p_scheduled_date < (clock_timestamp() at time zone p_exchange_timezone)::date then
    raise exception using errcode = '22007', message = 'scheduled_date_is_in_the_past';
  end if;

  insert into public.lifecycle_jobs (
    user_id, kind, status, scheduled_date, payload, resolved_symbol,
    exchange, exchange_timezone, next_attempt_at
  ) values (
    p_user_id, 'publish', 'pending', p_scheduled_date, p_payload,
    p_resolved_symbol, p_exchange, p_exchange_timezone, clock_timestamp()
  ) returning * into job_row;

  return to_jsonb(job_row);
end;
$$;

create or replace function public.update_scheduled_publication(
  p_job_id bigint,
  p_user_id uuid,
  p_payload jsonb,
  p_scheduled_date date,
  p_resolved_symbol text,
  p_exchange text,
  p_exchange_timezone text,
  p_activate boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  job_row public.lifecycle_jobs%rowtype;
begin
  select * into job_row
  from public.lifecycle_jobs
  where id = p_job_id and user_id = p_user_id and kind = 'publish'
  for update;

  if not found then return null; end if;
  if job_row.status = 'completed' then
    raise exception using errcode = 'P0001', message = 'scheduled_publication_completed';
  end if;
  if job_row.status = 'processing' and job_row.lease_expires_at > clock_timestamp() then
    raise exception using errcode = 'P0001', message = 'scheduled_publication_processing';
  end if;
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception using errcode = '22023', message = 'invalid_scheduled_payload';
  end if;
  if p_scheduled_date is null
    or (p_activate and p_scheduled_date < (clock_timestamp() at time zone p_exchange_timezone)::date) then
    raise exception using errcode = '22007', message = 'scheduled_date_is_in_the_past';
  end if;

  update public.lifecycle_jobs
  set payload = p_payload,
      scheduled_date = p_scheduled_date,
      resolved_symbol = p_resolved_symbol,
      exchange = p_exchange,
      exchange_timezone = p_exchange_timezone,
      status = case when p_activate then 'pending' else 'draft' end,
      attempt_count = 0,
      retry_cycle = retry_cycle + 1,
      next_attempt_at = case when p_activate then clock_timestamp() else null end,
      lease_token = null,
      lease_expires_at = null,
      last_error_code = null,
      updated_at = clock_timestamp()
  where id = p_job_id
  returning * into job_row;

  return to_jsonb(job_row);
end;
$$;

create or replace function public.cancel_scheduled_publication(
  p_job_id bigint,
  p_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  job_row public.lifecycle_jobs%rowtype;
begin
  select * into job_row
  from public.lifecycle_jobs
  where id = p_job_id and user_id = p_user_id and kind = 'publish'
  for update;

  if not found then return null; end if;
  if job_row.status = 'completed' then
    raise exception using errcode = 'P0001', message = 'scheduled_publication_completed';
  end if;
  if job_row.status = 'processing' and job_row.lease_expires_at > clock_timestamp() then
    raise exception using errcode = 'P0001', message = 'scheduled_publication_processing';
  end if;

  update public.lifecycle_jobs
  set status = 'draft',
      next_attempt_at = null,
      attempt_count = 0,
      lease_token = null,
      lease_expires_at = null,
      last_error_code = null,
      updated_at = clock_timestamp()
  where id = p_job_id
  returning * into job_row;

  return to_jsonb(job_row);
end;
$$;

create or replace function public.delete_scheduled_publication(
  p_job_id bigint,
  p_user_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  job_row public.lifecycle_jobs%rowtype;
begin
  select * into job_row
  from public.lifecycle_jobs
  where id = p_job_id and user_id = p_user_id and kind = 'publish'
  for update;

  if not found then return false; end if;
  if job_row.status = 'completed' then
    raise exception using errcode = 'P0001', message = 'scheduled_publication_completed';
  end if;
  if job_row.status = 'processing' and job_row.lease_expires_at > clock_timestamp() then
    raise exception using errcode = 'P0001', message = 'scheduled_publication_processing';
  end if;

  delete from public.lifecycle_jobs where id = p_job_id;
  return true;
end;
$$;

create or replace function public.retry_lifecycle_job(
  p_job_id bigint,
  p_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  job_row public.lifecycle_jobs%rowtype;
begin
  select * into job_row
  from public.lifecycle_jobs
  where id = p_job_id and user_id = p_user_id
  for update;

  if not found then return null; end if;
  if job_row.status <> 'action_required' then
    raise exception using errcode = 'P0001', message = 'lifecycle_job_not_retryable';
  end if;

  update public.lifecycle_jobs
  set status = 'pending',
      attempt_count = 0,
      retry_cycle = retry_cycle + 1,
      next_attempt_at = clock_timestamp(),
      lease_token = null,
      lease_expires_at = null,
      last_error_code = null,
      updated_at = clock_timestamp()
  where id = p_job_id
  returning * into job_row;

  return to_jsonb(job_row);
end;
$$;

create or replace function public.claim_lifecycle_jobs(
  p_lease_token uuid,
  p_limit integer default 25
)
returns setof public.lifecycle_jobs
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  return query
  with candidates as (
    select id
    from public.lifecycle_jobs
    where (
        status = 'pending'
        or (status = 'processing' and lease_expires_at <= clock_timestamp())
      )
      and next_attempt_at <= clock_timestamp()
      and scheduled_date <= (
        clock_timestamp() at time zone coalesce(nullif(exchange_timezone, ''), 'UTC')
      )::date
    order by next_attempt_at, id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 25), 25))
  )
  update public.lifecycle_jobs as jobs
  set status = 'processing',
      lease_token = p_lease_token,
      lease_expires_at = clock_timestamp() + interval '10 minutes',
      updated_at = clock_timestamp()
  from candidates
  where jobs.id = candidates.id
  returning jobs.*;
end;
$$;

create or replace function public.release_lifecycle_job(
  p_job_id bigint,
  p_lease_token uuid,
  p_delay_seconds integer default 60
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.lifecycle_jobs
  set status = 'pending',
      next_attempt_at = clock_timestamp() + make_interval(secs => greatest(30, p_delay_seconds)),
      lease_token = null,
      lease_expires_at = null,
      updated_at = clock_timestamp()
  where id = p_job_id and status = 'processing' and lease_token = p_lease_token;
  return found;
end;
$$;

create or replace function public.fail_lifecycle_job(
  p_job_id bigint,
  p_lease_token uuid,
  p_error_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  job_row public.lifecycle_jobs%rowtype;
  next_count integer;
  next_status text;
  retry_delay interval;
begin
  select * into job_row
  from public.lifecycle_jobs
  where id = p_job_id and status = 'processing' and lease_token = p_lease_token
  for update;
  if not found then return null; end if;

  next_count := job_row.attempt_count + 1;
  next_status := case when next_count >= 10 then 'action_required' else 'pending' end;
  retry_delay := case next_count
    when 1 then interval '15 minutes'
    when 2 then interval '30 minutes'
    when 3 then interval '1 hour'
    when 4 then interval '2 hours'
    when 5 then interval '4 hours'
    else interval '6 hours'
  end;

  update public.lifecycle_jobs
  set status = next_status,
      attempt_count = next_count,
      next_attempt_at = case when next_status = 'pending' then clock_timestamp() + retry_delay else null end,
      lease_token = null,
      lease_expires_at = null,
      last_error_code = left(coalesce(p_error_code, 'provider_unavailable'), 100),
      updated_at = clock_timestamp()
  where id = p_job_id;

  if next_status = 'action_required' then
    insert into public.notifications (
      user_id, type, title, message, thesis_id, lifecycle_job_id, event_key
    ) values (
      job_row.user_id,
      'action_required',
      'Scheduled action needs attention',
      case job_row.kind
        when 'publish' then 'Publication could not obtain valid market data. Review the schedule and retry.'
        else 'Scheduled close could not obtain valid market data. Retry when the feed is available.'
      end,
      job_row.thesis_id,
      job_row.id,
      format('lifecycle:%s:action:%s', job_row.id, job_row.retry_cycle)
    ) on conflict (event_key) do nothing;
  end if;

  return jsonb_build_object('status', next_status, 'attemptCount', next_count);
end;
$$;

create or replace function public.finalize_publication_job(
  p_job_id bigint,
  p_market jsonb,
  p_lease_token uuid default null,
  p_user_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  job_row public.lifecycle_jobs%rowtype;
  new_thesis public.theses%rowtype;
  published_at timestamptz := clock_timestamp();
  market_time timestamptz;
  market_date date;
  entry_price numeric;
  published_data jsonb;
begin
  select * into job_row
  from public.lifecycle_jobs
  where id = p_job_id and kind = 'publish'
  for update;
  if not found then return null; end if;

  if p_user_id is not null then
    if job_row.user_id <> p_user_id or job_row.status not in ('draft', 'pending', 'action_required') then
      raise exception using errcode = 'P0001', message = 'scheduled_publication_not_publishable';
    end if;
  elsif p_lease_token is null
    or job_row.status <> 'processing'
    or job_row.lease_token <> p_lease_token then
    raise exception using errcode = 'P0001', message = 'invalid_lifecycle_lease';
  end if;

  entry_price := nullif(p_market ->> 'price', '')::numeric;
  market_time := nullif(p_market ->> 'marketTime', '')::timestamptz;
  if entry_price is null or entry_price <= 0 or market_time is null then
    raise exception using errcode = '22023', message = 'invalid_market_snapshot';
  end if;
  if p_user_id is null and (
    coalesce(p_market ->> 'marketState', '') <> 'REGULAR'
    or market_time < clock_timestamp() - interval '30 minutes'
    or market_time > clock_timestamp() + interval '5 minutes'
  ) then
    raise exception using errcode = '22023', message = 'ineligible_market_snapshot';
  end if;
  market_date := (market_time at time zone job_row.exchange_timezone)::date;
  if market_date < job_row.scheduled_date and p_user_id is null then
    raise exception using errcode = '22023', message = 'market_snapshot_before_schedule';
  end if;

  published_data := job_row.payload || jsonb_build_object(
    'company', coalesce(nullif(job_row.payload ->> 'company', ''), p_market ->> 'company', job_row.resolved_symbol),
    'sector', coalesce(nullif(job_row.payload ->> 'sector', ''), p_market ->> 'sector', '—'),
    'publishDate', to_char(published_at at time zone job_row.exchange_timezone, 'Mon FMDD, YYYY'),
    'entryDate', market_date::text,
    'daysActive', 0,
    'entry', entry_price,
    'current', entry_price,
    'ret', 0,
    'status', 'active',
    'updates', 0,
    'currency', coalesce(nullif(p_market ->> 'currency', ''), 'USD'),
    'resolvedSymbol', coalesce(nullif(p_market ->> 'resolvedSymbol', ''), job_row.resolved_symbol),
    'exchange', coalesce(p_market ->> 'exchange', job_row.exchange),
    'createdAt', published_at
  );

  insert into public.theses (user_id, data, status, next_refresh_at)
  values (job_row.user_id, published_data, 'active', clock_timestamp())
  returning * into new_thesis;

  update public.lifecycle_jobs
  set status = 'completed',
      thesis_id = new_thesis.id,
      completed_at = published_at,
      next_attempt_at = null,
      lease_token = null,
      lease_expires_at = null,
      last_error_code = null,
      updated_at = published_at
  where id = job_row.id;

  insert into public.notifications (
    user_id, type, title, message, thesis_id, lifecycle_job_id, event_key
  ) values (
    job_row.user_id,
    'publication_completed',
    'Thesis published',
    format('%s was published and its entry price was sealed.', coalesce(job_row.payload ->> 'title', job_row.resolved_symbol)),
    new_thesis.id,
    job_row.id,
    format('lifecycle:%s:completed', job_row.id)
  ) on conflict (event_key) do nothing;

  return published_data || jsonb_build_object(
    'id', new_thesis.id,
    'ownerId', new_thesis.user_id,
    'lifecycleJobId', job_row.id
  );
end;
$$;

create or replace function public.schedule_thesis_close_job(
  p_thesis_id bigint,
  p_user_id uuid,
  p_close_date date,
  p_resolved_symbol text,
  p_exchange text,
  p_exchange_timezone text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  thesis_row public.theses%rowtype;
  job_row public.lifecycle_jobs%rowtype;
  updated_data jsonb;
begin
  if p_close_date is null
    or p_close_date <= (clock_timestamp() at time zone p_exchange_timezone)::date then
    raise exception using errcode = '22007', message = 'close_date_must_be_future';
  end if;

  select * into thesis_row
  from public.theses
  where id = p_thesis_id and user_id = p_user_id
  for update;

  if not found then return null; end if;
  if thesis_row.status = 'closed' then
    raise exception using errcode = 'P0001', message = 'thesis_already_closed';
  end if;
  if nullif(thesis_row.data ->> 'closeDate', '') is not null then
    raise exception using errcode = 'P0001', message = 'close_date_already_set';
  end if;

  updated_data := jsonb_set(thesis_row.data, '{closeDate}', to_jsonb(p_close_date::text), true);
  update public.theses
  set data = updated_data, version = version + 1
  where id = p_thesis_id;

  insert into public.lifecycle_jobs (
    user_id, kind, status, scheduled_date, thesis_id, resolved_symbol,
    exchange, exchange_timezone, next_attempt_at
  ) values (
    p_user_id, 'close', 'pending', p_close_date, p_thesis_id,
    p_resolved_symbol, p_exchange, p_exchange_timezone, clock_timestamp()
  ) returning * into job_row;

  return updated_data || jsonb_build_object(
    'id', thesis_row.id,
    'ownerId', thesis_row.user_id,
    'lifecycleJobId', job_row.id
  );
end;
$$;

create or replace function public.finalize_close_job(
  p_job_id bigint,
  p_market jsonb,
  p_lease_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  job_row public.lifecycle_jobs%rowtype;
  thesis_row public.theses%rowtype;
  entry_price numeric;
  close_price numeric;
  close_return numeric;
  market_time timestamptz;
  market_date date;
  closed_at timestamptz := clock_timestamp();
  updated_data jsonb;
begin
  select * into job_row
  from public.lifecycle_jobs
  where id = p_job_id and kind = 'close' and status = 'processing'
    and lease_token = p_lease_token
  for update;
  if not found then return null; end if;

  select * into thesis_row
  from public.theses
  where id = job_row.thesis_id and user_id = job_row.user_id
  for update;
  if not found then return null; end if;

  if thesis_row.status = 'closed' then
    update public.lifecycle_jobs
    set status = 'completed', completed_at = clock_timestamp(), next_attempt_at = null,
        lease_token = null, lease_expires_at = null, updated_at = clock_timestamp()
    where id = job_row.id;
    return thesis_row.data || jsonb_build_object('id', thesis_row.id, 'ownerId', thesis_row.user_id);
  end if;

  close_price := nullif(p_market ->> 'price', '')::numeric;
  market_time := nullif(p_market ->> 'marketTime', '')::timestamptz;
  if close_price is null or close_price <= 0 or market_time is null then
    raise exception using errcode = '22023', message = 'invalid_market_snapshot';
  end if;
  if coalesce(p_market ->> 'marketState', '') <> 'REGULAR'
    or market_time < clock_timestamp() - interval '30 minutes'
    or market_time > clock_timestamp() + interval '5 minutes' then
    raise exception using errcode = '22023', message = 'ineligible_market_snapshot';
  end if;
  market_date := (market_time at time zone job_row.exchange_timezone)::date;
  if market_date < job_row.scheduled_date then
    raise exception using errcode = '22023', message = 'market_snapshot_before_schedule';
  end if;

  entry_price := nullif(thesis_row.data ->> 'entry', '')::numeric;
  close_return := case
    when entry_price is null or entry_price = 0 then coalesce((thesis_row.data ->> 'ret')::numeric, 0)
    else round(
      (case when thesis_row.data ->> 'side' = 'bear' then -1 else 1 end)
      * ((close_price - entry_price) / entry_price) * 100,
      1
    )
  end;

  updated_data := thesis_row.data || jsonb_build_object(
    'status', 'closed',
    'closedAt', closed_at,
    'closePrice', close_price,
    'closeReturn', close_return,
    'current', close_price,
    'ret', close_return,
    'daysActive', greatest(0, market_date - nullif(thesis_row.data ->> 'entryDate', '')::date)
  );

  update public.theses
  set data = updated_data,
      status = 'closed',
      version = version + 1,
      refresh_lease_token = null,
      refresh_lease_expires_at = null
  where id = thesis_row.id;

  update public.lifecycle_jobs
  set status = 'completed', completed_at = closed_at, next_attempt_at = null,
      lease_token = null, lease_expires_at = null, last_error_code = null,
      updated_at = clock_timestamp()
  where id = job_row.id;

  insert into public.notifications (
    user_id, type, title, message, thesis_id, lifecycle_job_id, event_key
  ) values (
    job_row.user_id,
    'close_completed',
    'Thesis closed',
    format('%s closed automatically at its first eligible market session.', coalesce(thesis_row.data ->> 'title', job_row.resolved_symbol)),
    thesis_row.id,
    job_row.id,
    format('lifecycle:%s:completed', job_row.id)
  ) on conflict (event_key) do nothing;

  return updated_data || jsonb_build_object('id', thesis_row.id, 'ownerId', thesis_row.user_id);
end;
$$;

create or replace function public.claim_thesis_refreshes(
  p_lease_token uuid,
  p_limit integer default 25
)
returns table (id bigint, user_id uuid, data jsonb, lease_token uuid)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  return query
  with candidates as (
    select theses.id
    from public.theses
    where theses.status = 'active'
      and theses.next_refresh_at <= clock_timestamp()
      and (theses.refresh_lease_expires_at is null or theses.refresh_lease_expires_at <= clock_timestamp())
    order by theses.next_refresh_at, theses.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 25), 25))
  )
  update public.theses as theses
  set refresh_lease_token = p_lease_token,
      refresh_lease_expires_at = clock_timestamp() + interval '10 minutes'
  from candidates
  where theses.id = candidates.id
  returning theses.id, theses.user_id, theses.data, theses.refresh_lease_token;
end;
$$;

create or replace function public.apply_thesis_refresh(
  p_thesis_id bigint,
  p_lease_token uuid,
  p_patch jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  thesis_row public.theses%rowtype;
  updated_data jsonb;
  old_triggers jsonb;
  new_triggers jsonb;
  trigger_index integer;
  old_status text;
  new_status text;
  trigger_condition text;
  notification_title text;
begin
  if coalesce(p_patch, '{}'::jsonb) - array['current', 'ret', 'daysActive', 'triggers'] <> '{}'::jsonb then
    raise exception using errcode = '22023', message = 'unsupported_metrics_patch';
  end if;

  select * into thesis_row
  from public.theses
  where id = p_thesis_id and status = 'active' and refresh_lease_token = p_lease_token
  for update;
  if not found then return null; end if;

  old_triggers := case
    when jsonb_typeof(thesis_row.data -> 'triggers') = 'array' then thesis_row.data -> 'triggers'
    else '[]'::jsonb
  end;
  new_triggers := case
    when jsonb_typeof(p_patch -> 'triggers') = 'array' then p_patch -> 'triggers'
    else old_triggers
  end;

  if jsonb_array_length(new_triggers) > 0 then
    for trigger_index in 0..jsonb_array_length(new_triggers) - 1 loop
      old_status := coalesce(old_triggers -> trigger_index ->> 's', 'clear');
      new_status := coalesce(new_triggers -> trigger_index ->> 's', 'clear');
      if old_status is distinct from new_status and new_status in ('clear', 'warning', 'breached') then
        trigger_condition := coalesce(new_triggers -> trigger_index ->> 'c', 'A thesis trigger');
        notification_title := case new_status
          when 'breached' then 'Trigger breached'
          when 'warning' then 'Trigger warning'
          else 'Trigger cleared'
        end;
        insert into public.notifications (
          user_id, type, title, message, thesis_id, event_key
        ) values (
          thesis_row.user_id,
          'trigger_' || new_status,
          notification_title,
          format('%s moved from %s to %s.', trigger_condition, old_status, new_status),
          thesis_row.id,
          format('trigger:%s:%s:%s:%s', thesis_row.id, thesis_row.version + 1, trigger_index, new_status)
        ) on conflict (event_key) do nothing;
      end if;
    end loop;
  end if;

  updated_data := thesis_row.data || coalesce(p_patch, '{}'::jsonb);
  update public.theses
  set data = updated_data,
      version = version + case when updated_data is distinct from thesis_row.data then 1 else 0 end,
      last_refreshed_at = clock_timestamp(),
      next_refresh_at = clock_timestamp() + interval '15 minutes',
      refresh_failure_count = 0,
      refresh_lease_token = null,
      refresh_lease_expires_at = null
  where id = thesis_row.id;

  return updated_data || jsonb_build_object('id', thesis_row.id, 'ownerId', thesis_row.user_id);
end;
$$;

create or replace function public.fail_thesis_refresh(
  p_thesis_id bigint,
  p_lease_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.theses
  set next_refresh_at = clock_timestamp() + interval '15 minutes',
      refresh_failure_count = refresh_failure_count + 1,
      refresh_lease_token = null,
      refresh_lease_expires_at = null
  where id = p_thesis_id and status = 'active' and refresh_lease_token = p_lease_token;
  return found;
end;
$$;

-- Manual closes supersede any outstanding automatic-close job.
create or replace function public.close_thesis(
  p_thesis_id bigint,
  p_user_id uuid,
  p_close_price numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  thesis_row public.theses%rowtype;
  entry_price numeric;
  close_return numeric;
  active_days integer;
  closed_at timestamptz := clock_timestamp();
  updated_data jsonb;
begin
  select * into thesis_row
  from public.theses
  where id = p_thesis_id and user_id = p_user_id
  for update;

  if not found then return null; end if;
  if thesis_row.status = 'closed' then
    raise exception using errcode = 'P0001', message = 'thesis_already_closed';
  end if;
  if p_close_price is null or p_close_price <= 0 then
    raise exception using errcode = '22003', message = 'invalid_close_price';
  end if;

  entry_price := nullif(thesis_row.data ->> 'entry', '')::numeric;
  close_return := case
    when entry_price is null or entry_price = 0 then coalesce((thesis_row.data ->> 'ret')::numeric, 0)
    else round(
      (case when thesis_row.data ->> 'side' = 'bear' then -1 else 1 end)
      * ((p_close_price - entry_price) / entry_price) * 100,
      1
    )
  end;
  active_days := greatest(0, current_date - nullif(thesis_row.data ->> 'entryDate', '')::date);

  updated_data := thesis_row.data || jsonb_build_object(
    'status', 'closed',
    'closedAt', closed_at,
    'closePrice', p_close_price,
    'closeReturn', close_return,
    'current', p_close_price,
    'ret', close_return,
    'daysActive', active_days
  );

  update public.theses
  set data = updated_data, status = 'closed', version = version + 1,
      refresh_lease_token = null, refresh_lease_expires_at = null
  where id = p_thesis_id and user_id = p_user_id;

  update public.lifecycle_jobs
  set status = 'completed', completed_at = closed_at, next_attempt_at = null,
      lease_token = null, lease_expires_at = null, last_error_code = null,
      updated_at = closed_at
  where thesis_id = p_thesis_id and kind = 'close' and status <> 'completed';

  return updated_data || jsonb_build_object('id', thesis_row.id, 'ownerId', thesis_row.user_id);
end;
$$;

-- Create worker records for valid close dates sealed before this migration.
-- Their timezone is resolved by the worker from the current market snapshot.
with legacy_close_dates as (
  select
    theses.*,
    case when data ->> 'closeDate' ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then
      case when substring(data ->> 'closeDate', 1, 4)::integer between 1970 and 9999
        and substring(data ->> 'closeDate', 6, 2)::integer between 1 and 12
        and substring(data ->> 'closeDate', 9, 2)::integer between 1 and 31 then
        case when to_char(to_date(data ->> 'closeDate', 'YYYY-MM-DD'), 'YYYY-MM-DD') = data ->> 'closeDate'
          then to_date(data ->> 'closeDate', 'YYYY-MM-DD')
          else null
        end
      else null
      end
    else null
    end as parsed_close_date
  from public.theses
)
insert into public.lifecycle_jobs (
  user_id, kind, status, scheduled_date, thesis_id, resolved_symbol,
  exchange, exchange_timezone, next_attempt_at
)
select
  user_id,
  'close',
  'pending',
  parsed_close_date,
  id,
  coalesce(nullif(data ->> 'resolvedSymbol', ''), nullif(data ->> 'ticker', ''), 'UNKNOWN'),
  data ->> 'exchange',
  'UTC',
  clock_timestamp()
from legacy_close_dates as theses
where status = 'active'
  and parsed_close_date is not null
  and not exists (
    select 1 from public.lifecycle_jobs jobs
    where jobs.kind = 'close' and jobs.thesis_id = theses.id and jobs.status <> 'completed'
  );

create or replace view public.published_theses as
select
  t.id,
  t.user_id as owner_id,
  t.created_at,
  t.version,
  t.status,
  t.data ->> 'title' as title,
  t.data ->> 'ticker' as ticker,
  t.data ->> 'company' as company,
  t.data ->> 'side' as side,
  t.data ->> 'sector' as sector,
  t.data ->> 'publishDate' as publish_date,
  t.data ->> 'entryDate' as entry_date,
  t.data -> 'daysActive' as days_active,
  t.data -> 'entry' as entry,
  t.data -> 'current' as current_price,
  t.data -> 'ret' as return_pct,
  t.data -> 'updates' as updates,
  t.data -> 'triggers' as triggers,
  t.data ->> 'currency' as currency,
  t.data ->> 'resolvedSymbol' as resolved_symbol,
  t.data ->> 'exchange' as exchange,
  t.data ->> 'body' as body,
  t.data -> 'model' as model,
  t.data ->> 'createdAt' as thesis_created_at,
  t.data ->> 'closeDate' as close_date,
  t.data ->> 'closedAt' as closed_at,
  t.data -> 'closePrice' as close_price,
  t.data -> 'closeReturn' as close_return,
  t.data -> 'updateLog' as update_log,
  p.name as author_name,
  p.handle as author_handle,
  p.avatar as author_avatar,
  t.last_refreshed_at
from public.theses t
left join public.profiles p on p.id = t.user_id
where t.status in ('active', 'closed');

revoke all on public.published_theses from public;
grant select on public.published_theses to anon, authenticated, service_role;

revoke all on function public.create_scheduled_publication(uuid, jsonb, date, text, text, text) from public, anon, authenticated;
revoke all on function public.update_scheduled_publication(bigint, uuid, jsonb, date, text, text, text, boolean) from public, anon, authenticated;
revoke all on function public.cancel_scheduled_publication(bigint, uuid) from public, anon, authenticated;
revoke all on function public.delete_scheduled_publication(bigint, uuid) from public, anon, authenticated;
revoke all on function public.retry_lifecycle_job(bigint, uuid) from public, anon, authenticated;
revoke all on function public.claim_lifecycle_jobs(uuid, integer) from public, anon, authenticated;
revoke all on function public.release_lifecycle_job(bigint, uuid, integer) from public, anon, authenticated;
revoke all on function public.fail_lifecycle_job(bigint, uuid, text) from public, anon, authenticated;
revoke all on function public.finalize_publication_job(bigint, jsonb, uuid, uuid) from public, anon, authenticated;
revoke all on function public.schedule_thesis_close_job(bigint, uuid, date, text, text, text) from public, anon, authenticated;
revoke all on function public.finalize_close_job(bigint, jsonb, uuid) from public, anon, authenticated;
revoke all on function public.claim_thesis_refreshes(uuid, integer) from public, anon, authenticated;
revoke all on function public.apply_thesis_refresh(bigint, uuid, jsonb) from public, anon, authenticated;
revoke all on function public.fail_thesis_refresh(bigint, uuid) from public, anon, authenticated;

grant execute on function public.create_scheduled_publication(uuid, jsonb, date, text, text, text) to service_role;
grant execute on function public.update_scheduled_publication(bigint, uuid, jsonb, date, text, text, text, boolean) to service_role;
grant execute on function public.cancel_scheduled_publication(bigint, uuid) to service_role;
grant execute on function public.delete_scheduled_publication(bigint, uuid) to service_role;
grant execute on function public.retry_lifecycle_job(bigint, uuid) to service_role;
grant execute on function public.claim_lifecycle_jobs(uuid, integer) to service_role;
grant execute on function public.release_lifecycle_job(bigint, uuid, integer) to service_role;
grant execute on function public.fail_lifecycle_job(bigint, uuid, text) to service_role;
grant execute on function public.finalize_publication_job(bigint, jsonb, uuid, uuid) to service_role;
grant execute on function public.schedule_thesis_close_job(bigint, uuid, date, text, text, text) to service_role;
grant execute on function public.finalize_close_job(bigint, jsonb, uuid) to service_role;
grant execute on function public.claim_thesis_refreshes(uuid, integer) to service_role;
grant execute on function public.apply_thesis_refresh(bigint, uuid, jsonb) to service_role;
grant execute on function public.fail_thesis_refresh(bigint, uuid) to service_role;

commit;
