begin;

create table if not exists public.thesis_comments (
  id bigint generated by default as identity primary key,
  thesis_id bigint not null references public.theses (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  parent_id bigint references public.thesis_comments (id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 2000),
  status text not null default 'visible' check (status in ('visible', 'removed')),
  removed_by uuid references auth.users (id) on delete set null,
  removed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint thesis_comments_removal_state check (
    (status = 'visible' and removed_by is null and removed_at is null)
    or (status = 'removed' and removed_by is not null and removed_at is not null)
  )
);

create index if not exists thesis_comments_thread_idx
  on public.thesis_comments (thesis_id, created_at, id);
create index if not exists thesis_comments_author_recent_idx
  on public.thesis_comments (user_id, created_at desc);

create table if not exists public.comment_reports (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.thesis_comments (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  reason text not null check (reason in ('spam', 'harassment', 'misinformation', 'other')),
  details text not null default '' check (char_length(details) <= 500),
  created_at timestamptz not null default now(),
  constraint comment_reports_reporter_unique unique (comment_id, user_id)
);

create index if not exists comment_reports_comment_idx
  on public.comment_reports (comment_id, created_at desc);

alter table public.thesis_comments enable row level security;
alter table public.comment_reports enable row level security;

-- Discussion rows are served only through authenticated, validated API routes.
-- The service role performs those operations; browser roles receive no direct
-- table privileges, preventing clients from bypassing moderation rules.
revoke all on public.thesis_comments from public, anon, authenticated;
revoke all on public.comment_reports from public, anon, authenticated;
grant select, insert, update on public.thesis_comments to service_role;
grant select, insert on public.comment_reports to service_role;
grant usage, select on sequence public.thesis_comments_id_seq to service_role;
grant usage, select on sequence public.comment_reports_id_seq to service_role;

create or replace function public.enforce_thesis_comment_integrity()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  parent_row public.thesis_comments%rowtype;
begin
  if tg_op = 'INSERT' then
    if not exists (
      select 1 from public.theses
      where id = new.thesis_id and status in ('active', 'closed')
    ) then
      raise exception using errcode = '23514', message = 'comments_require_published_thesis';
    end if;

    if new.parent_id is not null then
      select * into parent_row from public.thesis_comments where id = new.parent_id;
      if not found or parent_row.thesis_id <> new.thesis_id then
        raise exception using errcode = '23514', message = 'reply_parent_must_share_thesis';
      end if;
      if parent_row.parent_id is not null then
        raise exception using errcode = '23514', message = 'replies_must_target_root_comment';
      end if;
      if parent_row.status <> 'visible' then
        raise exception using errcode = '23514', message = 'cannot_reply_to_removed_comment';
      end if;
    end if;

    new.body := btrim(new.body);
    new.status := 'visible';
    new.removed_by := null;
    new.removed_at := null;
    return new;
  end if;

  if new.thesis_id is distinct from old.thesis_id
    or new.user_id is distinct from old.user_id
    or new.parent_id is distinct from old.parent_id
    or new.body is distinct from old.body
    or new.created_at is distinct from old.created_at then
    raise exception using errcode = '23514', message = 'comment_content_is_immutable';
  end if;
  if old.status = 'removed' or new.status <> 'removed'
    or new.removed_by is null or new.removed_at is null then
    raise exception using errcode = '23514', message = 'invalid_comment_moderation_transition';
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_thesis_comment_integrity on public.thesis_comments;
create trigger enforce_thesis_comment_integrity
before insert or update on public.thesis_comments
for each row execute function public.enforce_thesis_comment_integrity();

create or replace function public.enforce_comment_report_integrity()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not exists (
    select 1 from public.thesis_comments
    where id = new.comment_id and status = 'visible' and user_id <> new.user_id
  ) then
    raise exception using errcode = '23514', message = 'comment_cannot_be_reported';
  end if;
  new.details := btrim(new.details);
  return new;
end;
$$;

drop trigger if exists enforce_comment_report_integrity on public.comment_reports;
create trigger enforce_comment_report_integrity
before insert on public.comment_reports
for each row execute function public.enforce_comment_report_integrity();

alter table public.notifications drop constraint if exists notifications_type_check;
alter table public.notifications add constraint notifications_type_check check (type in (
  'publication_completed', 'close_completed', 'trigger_clear',
  'trigger_warning', 'trigger_breached', 'action_required',
  'followed_publication', 'thesis_update', 'watched_close', 'watched_trigger',
  'discussion_comment', 'discussion_reply'
));

create or replace function public.notify_thesis_discussion()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  thesis_owner uuid;
  parent_author uuid;
  thesis_ticker text;
  recipient uuid;
begin
  select user_id, coalesce(nullif(data ->> 'ticker', ''), 'Thesis')
    into thesis_owner, thesis_ticker
  from public.theses where id = new.thesis_id;

  if new.parent_id is not null then
    select user_id into parent_author from public.thesis_comments where id = new.parent_id;
  end if;

  for recipient in
    select distinct candidate.user_id
    from (values (thesis_owner), (parent_author)) as candidate(user_id)
    where candidate.user_id is not null and candidate.user_id <> new.user_id
  loop
    insert into public.notifications (user_id, type, title, message, thesis_id, event_key)
    values (
      recipient,
      case when recipient = parent_author then 'discussion_reply' else 'discussion_comment' end,
      case when recipient = parent_author then 'New reply to your comment' else 'New thesis comment' end,
      format('%s received a new discussion %s.', thesis_ticker, case when recipient = parent_author then 'reply' else 'comment' end),
      new.thesis_id,
      format('discussion:comment:%s:%s', new.id, recipient)
    )
    on conflict (event_key) do nothing;
  end loop;
  return new;
end;
$$;

drop trigger if exists notify_thesis_discussion on public.thesis_comments;
create trigger notify_thesis_discussion
after insert on public.thesis_comments
for each row execute function public.notify_thesis_discussion();

revoke all on function public.enforce_thesis_comment_integrity() from public, anon, authenticated;
revoke all on function public.enforce_comment_report_integrity() from public, anon, authenticated;
revoke all on function public.notify_thesis_discussion() from public, anon, authenticated;

commit;
