begin;

create table if not exists public.saved_searches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  query text not null default '' check (char_length(query) <= 100),
  sector text not null default 'all' check (char_length(sector) between 1 and 80),
  side text not null default 'all' check (side in ('all', 'bull', 'bear')),
  thesis_status text not null default 'all' check (thesis_status in ('all', 'active', 'closed')),
  published_period text not null default 'all' check (published_period in ('all', '7d', '30d', '90d', '1y')),
  performance text not null default 'all' check (performance in ('all', 'positive', 'negative', '10plus')),
  sort text not null default 'trending' check (sort in ('trending', 'newest', 'top', 'activity', 'discussed', 'popular')),
  notify_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists saved_searches_owner_name_unique
  on public.saved_searches (user_id, lower(name));
create index if not exists saved_searches_owner_updated_idx
  on public.saved_searches (user_id, updated_at desc, id desc);
create index if not exists saved_searches_notifications_idx
  on public.saved_searches (notify_enabled, id)
  where notify_enabled = true;

alter table public.saved_searches enable row level security;
drop policy if exists "Users manage their own saved searches" on public.saved_searches;
create policy "Users manage their own saved searches"
  on public.saved_searches for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

revoke all on public.saved_searches from public, anon, authenticated;
grant select, insert, update, delete on public.saved_searches to authenticated;
grant usage, select on sequence public.saved_searches_id_seq to authenticated;

create or replace function public.enforce_saved_search_integrity()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  new.name := btrim(new.name);
  new.query := btrim(new.query);
  new.sector := btrim(new.sector);
  if tg_op = 'INSERT' then
    if (select count(*) from public.saved_searches where user_id = new.user_id) >= 20 then
      raise exception using errcode = '23514', message = 'saved_search_limit_reached';
    end if;
  elsif new.user_id is distinct from old.user_id or new.created_at is distinct from old.created_at then
    raise exception using errcode = '23514', message = 'saved_search_owner_is_immutable';
  end if;
  new.updated_at := clock_timestamp();
  return new;
end;
$$;

drop trigger if exists enforce_saved_search_integrity on public.saved_searches;
create trigger enforce_saved_search_integrity
before insert or update on public.saved_searches
for each row execute function public.enforce_saved_search_integrity();

alter table public.notifications drop constraint if exists notifications_type_check;
alter table public.notifications add constraint notifications_type_check check (type in (
  'publication_completed', 'close_completed', 'trigger_clear',
  'trigger_warning', 'trigger_breached', 'action_required',
  'followed_publication', 'thesis_update', 'watched_close', 'watched_trigger',
  'discussion_comment', 'discussion_reply', 'saved_search_match'
));

create or replace function public.notify_saved_search_matches()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  saved public.saved_searches%rowtype;
  search_text text;
  thesis_return numeric;
begin
  if new.status not in ('active', 'closed') then return new; end if;

  search_text := lower(concat_ws(' ',
    new.data ->> 'title', new.data ->> 'ticker', new.data ->> 'company',
    new.data ->> 'sector', regexp_replace(coalesce(new.data ->> 'body', ''), '<[^>]+>', ' ', 'g'),
    (select name from public.profiles where id = new.user_id),
    (select handle from public.profiles where id = new.user_id)
  ));
  thesis_return := coalesce(nullif(new.data ->> 'ret', '')::numeric, 0);

  for saved in
    select * from public.saved_searches
    where notify_enabled = true and user_id <> new.user_id
  loop
    if saved.query <> '' and position(lower(saved.query) in search_text) = 0 then continue; end if;
    if saved.sector <> 'all' and saved.sector <> coalesce(new.data ->> 'sector', '') then continue; end if;
    if saved.side <> 'all' and saved.side <> coalesce(new.data ->> 'side', '') then continue; end if;
    if saved.thesis_status <> 'all' and saved.thesis_status <> new.status then continue; end if;
    if saved.performance = 'positive' and thesis_return <= 0 then continue; end if;
    if saved.performance = 'negative' and thesis_return >= 0 then continue; end if;
    if saved.performance = '10plus' and thesis_return < 10 then continue; end if;

    insert into public.notifications (user_id, type, title, message, thesis_id, event_key)
    values (
      saved.user_id,
      'saved_search_match',
      format('New match for %s', saved.name),
      format('%s: %s', coalesce(nullif(new.data ->> 'ticker', ''), 'Thesis'), coalesce(nullif(new.data ->> 'title', ''), 'New investment thesis')),
      new.id,
      format('saved-search:%s:thesis:%s', saved.id, new.id)
    )
    on conflict (event_key) do nothing;
  end loop;
  return new;
end;
$$;

drop trigger if exists notify_saved_search_matches on public.theses;
create trigger notify_saved_search_matches
after insert on public.theses
for each row execute function public.notify_saved_search_matches();

-- Append aggregate engagement counts to the explicit public projection. The
-- underlying viewer identities and report records remain private.
create or replace view public.published_theses as
select
  t.id,
  t.user_id as owner_id,
  t.created_at,
  t.version,
  t.status,
  t.data ->> 'title' as title,
  t.data ->> 'ticker' as ticker,
  t.data ->> 'company' as company,
  t.data ->> 'side' as side,
  t.data ->> 'sector' as sector,
  t.data ->> 'publishDate' as publish_date,
  t.data ->> 'entryDate' as entry_date,
  t.data -> 'daysActive' as days_active,
  t.data -> 'entry' as entry,
  t.data -> 'current' as current_price,
  t.data -> 'ret' as return_pct,
  t.data -> 'updates' as updates,
  t.data -> 'triggers' as triggers,
  t.data ->> 'currency' as currency,
  t.data ->> 'resolvedSymbol' as resolved_symbol,
  t.data ->> 'exchange' as exchange,
  t.data ->> 'body' as body,
  t.data -> 'model' as model,
  t.data ->> 'createdAt' as thesis_created_at,
  t.data ->> 'closeDate' as close_date,
  t.data ->> 'closedAt' as closed_at,
  t.data -> 'closePrice' as close_price,
  t.data -> 'closeReturn' as close_return,
  t.data -> 'updateLog' as update_log,
  p.name as author_name,
  p.handle as author_handle,
  p.avatar as author_avatar,
  t.last_refreshed_at,
  p.slug as author_slug,
  t.data -> 'citations' as citations,
  (select count(*) from public.thesis_comments comments where comments.thesis_id = t.id and comments.status = 'visible') as comment_count,
  (select count(*) from public.thesis_bookmarks bookmarks where bookmarks.thesis_id = t.id) as bookmark_count
from public.theses t
left join public.profiles p on p.id = t.user_id
where t.status in ('active', 'closed');

revoke all on public.published_theses from public;
grant select on public.published_theses to anon, authenticated, service_role;

revoke all on function public.enforce_saved_search_integrity() from public, anon, authenticated;
revoke all on function public.notify_saved_search_matches() from public, anon, authenticated;

commit;
